### ISSUE TITLE
[FEAT]: Request for DPO 7k driver

### ISSUE THREAD

**Issue by FateDecider** [tektronix/tm_devices#124]
### Description

Would like to request for quick implementation of DPO 7k driver since there is already DPO 7kc driver in the library :)

**Comment by nfelt14** [comment]
Is this request purely for the basic control driver? Or is it a request for the full API commands implementation?

**Comment by u625355** [comment]
Since basic support is already available, enabling full API commands will be apt for this enhancement request.

**Comment by u625355** [comment]
DPO 7k driver is enabled in the latest version of tm_devices and available in pip package too https://pypi.org/project/tm-devices/
Hence, this issue will be closed.
