### ISSUE TITLE
[Bug]: IV Sweep Timeout Error

### ISSUE THREAD

**Issue by GaliumNick** [tektronix/tm_devices#277]
### Description of the bug

Hello, I am new to TSP. I have been using the Solar Panel Sweep sample code on my 2470. The function works but the program keeps stopping because of a PYVISA timeout error. I need a way to avoid PYVISA time limits, and I used a previous software that completely avoided PYVISA time constraint so it should be possible.

### Steps To Reproduce

Run smu_2460_solar_panel_sweep.py from 0 to 20V. 
`pyvisa.errors.Error: The query failed with the following message: VisaIOError('VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.')`

**Comment by nfelt14** [comment]
Have you tried setting the device timeout to something longer?

Snippet of code:
```python
with DeviceManager(verbose=False) as dm:
    inst: SMU2460 = dm.add_smu(RESOURCE_ID)
    inst.visa_timeout = 30_000  # 30 seconds
```

**Comment by GaliumNick** [comment]
I tried that and it still times out. Maybe I can tie that number to the nplc so it will know how long the sweep will take.

**Comment by nfelt14** [comment]
> I tried that and it still times out. Maybe I can tie that number to the nplc so it will know how long the sweep will take.

You could try a really large number as well, something like `30_000_000`

**Comment by GaliumNick** [comment]
That worked! Also, quick question, what is this code for?
# # Set the operation status bit 0 to high when the trigger model is active.
    # # See Event Numbers in 2460 reference manual.
    # inst.commands.status.operation.setmap(0, 2731, 2732)
    # inst.commands.trigger.model.initiate()

    # while True:  # This is needed to wait for the trigger model to complete
    #     time.sleep(0.5)
    #     if not int(inst.commands.status.operation.condition):
    #         break

**Comment by nfelt14** [comment]
> That worked! Also, quick question, what is this code for?
> 
> # # Set the operation status bit 0 to high when the trigger model is active.
> ```
> # # See Event Numbers in 2460 reference manual.
> # inst.commands.status.operation.setmap(0, 2731, 2732)
> # inst.commands.trigger.model.initiate()
> 
> # while True:  # This is needed to wait for the trigger model to complete
> #     time.sleep(0.5)
> #     if not int(inst.commands.status.operation.condition):
> #         break
> ```

Unfortunately, I am not an expert on that model. 😄 

@amccann-Tek, can you try to get an answer for this question?

**Comment by GaliumNick** [comment]
So I've gotten the sweeps to run but it stops at current limit. I tried changing the `fail_abort` parameter but it doesn't recognize `inst.commands.smu.OFF`.
`    inst.commands.smu.source.sweeplinearstep(config_list_name="RES", start=vstart, stop=vstop, step=vstep, s_delay=delay, fail_abort=inst.commands.smu.OFF)
    inst.commands.trigger.model.initiate()
    inst.commands.waitcomplete()`

**Comment by GaliumNick** [comment]
@nfelt14 Any idea how to turn off `fail_abort`? I set it to 0, '0', 'smu.OFF', 'False', False, inst.commands.smu.OFF with no effect. I don't want the sweep to stop when it reaches compliance.
