### ISSUE TITLE
[BUG]: TekScope2K - VERBOSE and HEADER options must be turned on to query the available data sources

### ISSUE THREAD

**Issue by RoaCode** [tektronix/tm_devices#326]
### Description of the bug

In the TekScope_2k.py driver file, the get_available_data_sources function will run into an error if VERBOSE and HEADER scope options are not enabled. Those options tell the scope to return descriptive strings as opposed to simple booleans. The driver is currently looking for the descriptive strings, so the drivers needs to ensure the correct state prior to calling SELECT?. The driver can disable those options afterwards.

### Steps To Reproduce

To produce error:

1. Ensure scope has VERBOSE and HEADER disabled.  "self.set_and_check("HEADER", "0")", "self.set_and_check("VERBOSE", "0")"
2. Call TekScope2k.get_available_data_sources() function

**Comment by nfelt14** [comment]
This was released in [v2.5.0](https://github.com/tektronix/tm_devices/releases/tag/v2.5.0)
